### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by abel-tefera** [abel-tefera/doctor-appointment-back-end#12]
[Link to board](https://github.com/abel-tefera/doctor-appointment-back-end/projects/1)

Note: We are a group of **four** members

_**Screenshot**_
![Screenshot 2023-09-20 165735](https://github.com/abel-tefera/doctor-appointment-back-end/assets/40035531/5dca672e-482c-4615-8ee1-72f6efecafdd)

**Comment by Meltrust** [comment]
Hi @abel-tefera,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been pointed, have descriptions, and assignees. ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] OPTIONAL:  You could add tags to the tasks to better categorize them. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
